// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportGenerator.Data;

namespace ReportGenerator.Migrations.ProjectParameters
{
    [DbContext(typeof(ProjectParametersContext))]
    partial class ProjectParametersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("ReportGenerator.Models.ProjectParameter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ALE")
                        .HasColumnType("REAL");

                    b.Property<double>("LOQ")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SignificantDigits")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SpecificationOne")
                        .HasColumnType("REAL");

                    b.Property<double?>("SpecificationOneConcRange")
                        .HasColumnType("REAL");

                    b.Property<double?>("SpecificationTwo")
                        .HasColumnType("REAL");

                    b.Property<double?>("SpecificationTwoConcRange")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Xc1")
                        .HasColumnType("REAL");

                    b.Property<double?>("Xc2")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("ProjectParameter");
                });
#pragma warning restore 612, 618
        }
    }
}
