// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportGenerator.Data;

namespace ReportGenerator.Migrations.ProjectParameters
{
    [DbContext(typeof(ProjectParametersContext))]
    [Migration("20200406030529_changeprojectparameterdbsource")]
    partial class changeprojectparameterdbsource
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReportGenerator.Models.ProjectParameter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ALE")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignificantDigits")
                        .HasColumnType("int");

                    b.Property<double>("Xc1")
                        .HasColumnType("float");

                    b.Property<double>("Xc2")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("ProjectParameter");
                });
#pragma warning restore 612, 618
        }
    }
}
